In [1]:
#import numpy Library
import numpy as np

In [2]:
#first numpy Array
first_numpy_array = np.array([1,2,3,4,5])

In [3]:
#Print first Array
print(first_numpy_array)

[1 2 3 4 5]


In [4]:
#Array with zeros
array_with_zero = np.zeros((3,3))
array_with_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#Array with ones
array_with_one = np.ones((3,3))
array_with_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#Array with empty
array_with_empty = np.empty((3,3))
array_with_empty

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#Array with arrange method
np_arrange = np.arange(12)

In [8]:
#print array
print(np_arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
#reshape method to change and create array
np_arrange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
#linespace for linearly (equal) spaced data element
np_linespace = np.linspace(1,5,10) #First element=1, Last element=5, Total number of equidistant elemnts =10


In [11]:
#print linespaced array
np_linespace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [12]:
#one Dimensional  array
one_d = np.arange(15)
one_d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# Two Dimensional array
two_d = one_d.reshape(3,5)
two_d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
#Three Dimensional array

In [15]:
three_d = np.arange(27).reshape(3,3,3)
three_d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

   # Classes and Attributes of ndarray
   * .ndim
   * .shape
   * .size
   * .dtype

In [31]:
# checking the dimenssion of above array 
print('Dimenssion of one_d is :-', one_d.ndim)
print('Dimenssion of two_d is :-', two_d.ndim)
print('Dimenssion of three_d is :-', three_d.ndim)

Dimenssion of one_d is :- 1
Dimenssion of two_d is :- 2
Dimenssion of three_d is :- 3


In [32]:
#checking the shape of above array
print('shape of one_d is :-', one_d.shape)
print('shape of two_d is :-', two_d.shape)
print('shape of three_d is :-', three_d.shape)

shape of one_d is :- (15,)
shape of two_d is :- (3, 5)
shape of three_d is :- (3, 3, 3)


In [34]:
#checking the size of above array
print('size of one_d is :-', one_d.size)
print('size of two_d is :-', two_d.size)
print('size of three_d is :-', three_d.size)

size of one_d is :- 15
size of two_d is :- 15
size of three_d is :- 27


In [35]:
#checking the dtype of above array
print('dtype of one_d is :-', one_d.dtype)
print('dtype of two_d is :-', two_d.dtype)
print('dtype of three_d is :-', three_d.dtype)

dtype of one_d is :- int64
dtype of two_d is :- int64
dtype of three_d is :- int64
